export interface ServerConfig {
  serverAddr: string;
  serverPort: number;
  authToken: string;
  subDomainHost: string;
  tlsEnabled: boolean;
  adminPort: number;
  adminUser: string;
  adminPassword: string;
  vhostHTTPPort: number;
  vhostHTTPSPort: number;
  /** 服务端管理页地址（如 http://vps:17500），用于拉取域名目录，简化隧道编辑。留空则走手填。 */
  managementURL?: string;
  /** 拉取 /api/domains 用的 Bearer token（对应服务端 MEILINK_DOMAIN_API_TOKEN）。 */
  domainAPIToken?: string;
  /** 自动重连：断连后每次探测/等待的间隔（秒）。默认 10，clamp [3, 300]。 */
  reconnectInterval?: number;
  /** 自动重连：重建连接连续失败多少次后升级为重启 frpc。默认 3，clamp [1, 30]。 */
  maxReconnectAttempts?: number;
  /** 自动重连：重启 frpc 连续失败多少次后放弃自动恢复。默认 3，clamp [1, 30]。 */
  maxRestartAttempts?: number;
}

export function generateFrpcToml(config: ServerConfig, dataDir: string): string {
  const tomlString = (value: string) => JSON.stringify(value);
  const pathSeparator = dataDir.includes("\\") ? "\\" : "/";
  const storePath = `${dataDir.replace(/[\\/]+$/, "")}${pathSeparator}store.json`;
  return [
    "# Auto-generated by Meilink",
    `serverAddr = ${tomlString(config.serverAddr)}`,
    `serverPort = ${config.serverPort}`,
    "",
    'auth.method = "token"',
    `auth.token = ${tomlString(config.authToken)}`,
    "",
    `transport.tls.enable = ${config.tlsEnabled}`,
    "transport.poolCount = 5",
    "transport.tcpMux = true",
    "transport.tcpMuxKeepaliveInterval = 30",
    "",
    'webServer.addr = "127.0.0.1"',
    `webServer.port = ${config.adminPort}`,
    `webServer.user = ${tomlString(config.adminUser)}`,
    `webServer.password = ${tomlString(config.adminPassword)}`,
    "",
    "[store]",
    `path = ${tomlString(storePath)}`,
    "",
    "# Proxies are managed dynamically via Store API",
    "",
  ].join("\n");
}
