export interface ServerConfig {
  serverAddr: string;
  serverPort: number;
  authToken: string;
  subDomainHost: string;
  tlsEnabled: boolean;
  adminPort: number;
  adminUser: string;
  adminPassword: string;
}

export function generateFrpcToml(config: ServerConfig, dataDir: string): string {
  const tomlString = (value: string) => JSON.stringify(value);
  const pathSeparator = dataDir.includes("\\") ? "\\" : "/";
  const storePath = `${dataDir.replace(/[\\/]+$/, "")}${pathSeparator}store.json`;
  return [
    "# Auto-generated by Meilink",
    `serverAddr = ${tomlString(config.serverAddr)}`,
    `serverPort = ${config.serverPort}`,
    "",
    'auth.method = "token"',
    `auth.token = ${tomlString(config.authToken)}`,
    "",
    `transport.tls.enable = ${config.tlsEnabled}`,
    "transport.poolCount = 5",
    "transport.tcpMux = true",
    "transport.tcpMuxKeepaliveInterval = 30",
    "",
    'webServer.addr = "127.0.0.1"',
    `webServer.port = ${config.adminPort}`,
    `webServer.user = ${tomlString(config.adminUser)}`,
    `webServer.password = ${tomlString(config.adminPassword)}`,
    "",
    "[store]",
    `path = ${tomlString(storePath)}`,
    "",
    "# Proxies are managed dynamically via Store API",
    "",
  ].join("\n");
}
