export type DomainKind = "primary" | "custom" | "wildcard";

export type ManagedDomain = {
  domain: string;
  kind: DomainKind;
  enabled: boolean;
};

export type ServerConfig = {
  bindPort: number;
  vhostHTTPPort: number;
  vhostHTTPSPort: number;
  authToken: string;
  domains: ManagedDomain[];
};

const hostPattern = /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;

function canonicalDomain(value: string) {
  return value.trim().toLowerCase().replace(/\.$/, "");
}

function assertDomain(domain: string, kind: DomainKind) {
  const wildcard = domain.startsWith("*.");
  const host = wildcard ? domain.slice(2) : domain;
  if (kind === "primary" && wildcard) throw new Error("主域名不能使用泛域名");
  if (kind === "wildcard" && !wildcard) throw new Error("泛域名必须以 *. 开头");
  if (kind !== "wildcard" && wildcard) throw new Error("泛域名必须使用泛域名类型");
  if (host.includes("*")) throw new Error("泛域名只能使用开头的 *. 通配符");
  if (!hostPattern.test(host)) throw new Error(`无效域名: ${domain}`);
}

export function normalizeDomains(input: ManagedDomain[]): ManagedDomain[] {
  const seen = new Set<string>();
  let primaryCount = 0;
  const domains = input.reduce<ManagedDomain[]>((domains, item) => {
    const domain = canonicalDomain(String(item.domain || ""));
    const kind = item.kind;
    const enabled = item.enabled !== false;
    assertDomain(domain, kind);
    if (kind === "primary" && enabled && ++primaryCount > 1) throw new Error("只能设置一个主域名");
    if (seen.has(domain)) return domains;
    seen.add(domain);
    domains.push({ domain, kind, enabled });
    return domains;
  }, []);
  const primary = domains.find((domain) => domain.kind === "primary" && domain.enabled)?.domain;
  if (primary && domains.some((domain) => domain.kind !== "primary" && domain.enabled && (domain.domain === primary || domain.domain.endsWith(`.${primary}`)))) {
    throw new Error("额外域名或泛域名不能属于主域名的子域名范围");
  }
  return domains;
}

function port(value: number, name: string) {
  if (!Number.isInteger(value) || value < 1 || value > 65535) throw new Error(`${name} 必须是 1-65535 的端口`);
  return value;
}

export function normalizeServerConfig(input: ServerConfig): ServerConfig {
  const authToken = String(input.authToken || "").trim();
  if (!authToken) throw new Error("FRP Token 不能为空");
  return {
    bindPort: port(Number(input.bindPort), "客户端连接端口"),
    vhostHTTPPort: port(Number(input.vhostHTTPPort), "HTTP 端口"),
    vhostHTTPSPort: port(Number(input.vhostHTTPSPort), "HTTPS 端口"),
    authToken,
    domains: normalizeDomains(Array.isArray(input.domains) ? input.domains : []),
  };
}

export function renderFrpsToml(config: ServerConfig): string {
  const normalized = normalizeServerConfig(config);
  const primary = normalized.domains.find((domain) => domain.kind === "primary" && domain.enabled);
  return [
    "# Generated by Meilink Server. Do not edit manually.",
    `bindPort = ${normalized.bindPort}`,
    `vhostHTTPPort = ${normalized.vhostHTTPPort}`,
    `vhostHTTPSPort = ${normalized.vhostHTTPSPort}`,
    ...(primary ? [`subDomainHost = ${JSON.stringify(primary.domain)}`] : []),
    "",
    'auth.method = "token"',
    `auth.token = ${JSON.stringify(normalized.authToken)}`,
    "",
  ].join("\n");
}

export function defaultServerConfig(env = process.env): ServerConfig {
  const primary = String(env.MEILINK_PRIMARY_DOMAIN || "").trim();
  const domains = primary ? [{ domain: primary, kind: "primary" as const, enabled: true }] : [];
  return {
    bindPort: Number(env.MEILINK_FRPS_BIND_PORT || 7000),
    vhostHTTPPort: Number(env.MEILINK_FRPS_HTTP_PORT || 8080),
    vhostHTTPSPort: Number(env.MEILINK_FRPS_HTTPS_PORT || 8443),
    authToken: String(env.MEILINK_FRPS_TOKEN || ""),
    domains,
  };
}
